tubee/routes/admin.py
from flask import current_app  # type: ignore
from flask import Blueprint, render_template
from flask_login import login_required

from .. import Tubee
from ..models import Channel
from ..tasks import list_all_tasks
from ..utils import admin_required, build_sitemap

current_app: Tubee

admin_blueprint = Blueprint("admin", __name__)
admin_blueprint.before_request(admin_required)


@admin_blueprint.get("/")
@login_required
def dashboard():
    links = build_sitemap()
    return render_template("admin/main.html", links=links, version=current_app.version)


@admin_blueprint.get("/channels")
def channels():
    channels = Channel.query.all()
    tasks = list_all_tasks()
    return render_template("admin/channels_page.html", channels=channels, tasks=tasks)

tubee/routes/main.py
"""The Main Routes"""

import bs4
from flask import Blueprint, jsonify, render_template, request
from flask_login import current_user  # type: ignore
from flask_login import login_required
from loguru import logger

from .. import db
from ..forms import ActionForm
from ..models import Callback, Channel, User, Video

current_user: User

main_blueprint = Blueprint("main", __name__)


@main_blueprint.get("/")
@login_required
def dashboard():
    """Showing Subscribed Channels with specified tag"""

    # Fetching all subscribed channels
    subscriptions = current_user.subscriptions.outerjoin(Channel).order_by(
        Channel.name.asc()
    )

    # Paginate subscriptions
    page = request.args.get("page", 1, type=int)
    pagination = subscriptions.paginate(page=page, per_page=25, error_out=False)
    return render_template(
        "subscription/main.html",
        subscription_pagination=pagination,
        tag=None,
        actions=None,
    )


@main_blueprint.get("/subscription/youtube")
@login_required
def youtube_subscription():
    return render_template("subscription/youtube.html")


@main_blueprint.get("/channel/<channel_id>")
def channel(channel_id):
    subscription = current_user.subscriptions.filter_by(
        channel_id=channel_id
    ).first_or_404()

    # Paginate videos
    page = request.args.get("page", 1, type=int)
    videos = subscription.channel.videos.order_by(Video.uploaded_timestamp.desc())
    pagination = videos.paginate(page=page, per_page=25, error_out=False)
    return render_template(
        "channel.html",
        subscription=subscription,
        action_form=ActionForm(),
        video_pagination=pagination,
    )


@main_blueprint.get("/channel/<channel_id>/callback")
def channel_callback_subscribe(channel_id):
    """Receive Hub Challenges to sustain subscription"""
    channel_item = Channel.query.get_or_404(channel_id)
    callback_item = Callback(channel_item)
    infos = {
        "method": request.method,
        "arguments": request.args,
        "user_agent": str(request.user_agent),
    }
    response = request.args.to_dict().get("hub.challenge")
    if response:
        callback_item.type = "Hub Challenge"
        infos["details"] = response
        callback_item.infos = infos
    else:
        response = callback_item.type = "Unknown GET Request"
    db.session.commit()
    return response


# TODO: REBUILD THIS
@main_blueprint.post("/channel/<channel_id>/callback")
def channel_callback(channel_id):
    """Receive Hub Notifications"""
    channel_item = Channel.query.get_or_404(channel_id)
    callback_item = Callback(channel_item)
    infos = {
        "method": request.method,
        "arguments": request.args,
        "user_agent": str(request.user_agent),
    }

    # Preprocessing
    infos["data"] = request.get_data(as_text=True)
    soup = bs4.BeautifulSoup(infos["data"], "xml")
    response = {}
    # TODO: Inspecting

    tag = soup.find("yt:videoId")
    if tag is None:
        logger.info(f"Video ID not Found for {callback_item}")
        callback_item.infos = infos
        db.session.commit()
        return response
    video_id = tag.string

    # Update Database Records
    video_item = Video.query.get(video_id)
    new_video = not bool(video_item)
    if new_video:
        video_item = Video(video_id, channel_item)
    video_item.callbacks.append(callback_item)
    callback_item.video = video_item
    callback_item.type = "Hub Notification"
    callback_item.infos = infos
    db.session.commit()

    # Pass actions if not new video
    if not new_video:
        return jsonify(response)

    # List users and execute actions
    for sub in channel_item.subscriptions:
        for action in sub.automated_actions:
            try:
                results = action.execute(
                    video_id=video_id,
                    video_title=video_item.name,
                    video_description=video_item.details["description"],
                    video_thumbnail=video_item.details["thumbnails"]["medium"]["url"],
                    video_thumbnail_small=video_item.details["thumbnails"]["default"][
                        "url"
                    ],
                    video_file_url=video_item.video_file_url,
                    channel_name=channel_item.name,
                )
            except Exception as error:
                results = {
                    "error": error.__class__.__name__,
                    "description": str(error),
                }
                logger.exception(f"{channel_id}-{action.id}: {error}")
            else:
                logger.info(f"{channel_id}-{action.id}")
            response[action.id] = results
    return jsonify(response)


@main_blueprint.get("/video")
@login_required
def video():
    return render_template("video/main.html")

tubee/routes/tag.py
from flask import Blueprint, render_template
from flask_login import current_user  # type: ignore
from flask_login import login_required

from ..models import Tag, User

current_user: User

tag_blueprint = Blueprint("tag", __name__)


@tag_blueprint.get("/")
@login_required
def listing():
    tags = current_user.tags.order_by(Tag.sort_index.asc()).all()
    subscriptions = current_user.subscriptions.all()
    return render_template("tag/listing.html", tags=tags, subscriptions=subscriptions)


@tag_blueprint.get("/<tag_id>")
@login_required
def main(tag_id: int):
    """Showing Subscribed Channels with specified tag"""
    tag = Tag.query.get_or_404(tag_id, "Tag not found")
    actions = current_user.actions.join(Tag).filter(Tag.id == tag_id).all()
    return render_template("tag/main.html", tag=tag, actions=actions)

tubee/routes/user.py
"""Routes involves user credentials"""

from dropbox.oauth import (
    BadRequestException,
    BadStateException,
    CsrfException,
    NotApprovedException,
    ProviderException,
)
from flask import (
    Blueprint,
    abort,
    flash,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from flask_login import current_user  # type: ignore
from flask_login import login_required, login_user, logout_user

from .. import oauth
from ..forms import UserForm
from ..models import User
from ..utils import dropbox, is_safe_url, youtube

current_user: User

user_blueprint = Blueprint("user", __name__)


@user_blueprint.get("/")
@login_required
def setting():
    """User Setting Page"""
    return render_template("user/setting.html")


@user_blueprint.route("/register", methods=["GET", "POST"])
def register():
    """User Register"""
    if current_user.is_authenticated:
        flash("You've already logined!", "success")
        return redirect(url_for("main.dashboard"))
    form = UserForm(submit_label="Register", password_confirm=True)
    if form.validate_on_submit():
        exist_user = User.query.get(form.username.data)
        if not exist_user:
            new_user = User(form.username.data, form.password.data)
            login_user(new_user)
            return redirect(url_for("main.dashboard"))
        flash("The Username is Taken", "warning")
    return render_template("user/register.html", form=form)


@user_blueprint.route("/login", methods=["GET", "POST"])
def login():
    """User Login"""
    if current_user.is_authenticated:
        flash("You've already logined!", "success")
        return redirect(url_for("main.dashboard"))
    form = UserForm(submit_label="Login")
    if form.is_submitted():
        if form.validate():
            query_user = User.query.get(form.username.data)
            if query_user and query_user.check_password(form.password.data):
                login_user(query_user, remember=True)
                redirect_url = request.args.get("next")
                if redirect_url and is_safe_url(redirect_url):
                    return redirect(redirect_url)
                return redirect(url_for("main.dashboard"))
        flash("Invalid username or password.", "warning")
    return render_template("user/login.html", form=form)


@user_blueprint.get("/logout")
@login_required
def logout():
    """User Logout"""
    logout_user()
    flash("You've Logged Out", "success")
    return redirect(url_for("user.login"))


@user_blueprint.route("/change-password", methods=["GET", "POST"])
@login_required
def change_password():
    """Change Password"""
    form = UserForm(
        username=current_user.username, submit_label="Save", password_confirm=True
    )
    if form.validate_on_submit():
        current_user.password = form.password.data
        flash("Password Changed", "success")
        return redirect(url_for("user.setting"))
    return render_template("user/change_password.html", form=form)


@user_blueprint.route("/delete", methods=["GET", "POST"])
@login_required
def delete():
    """Confirm Delete Account"""
    form = UserForm(username=current_user.username, submit_label="Delete")
    if form.validate_on_submit():
        if current_user.check_password(form.password.data):
            current_user.delete()
            logout_user()
            flash("Your Account has been deleted", "success")
            return redirect(url_for("user.login"))
        flash("Invalid username or password.", "warning")
    return render_template("user/delete.html", form=form)


@user_blueprint.get("/setting/youtube/authorize")
@login_required
def setting_youtube_authorize():
    flow = youtube.build_flow()
    authorization_url, state = flow.authorization_url(
        access_type="offline", include_granted_scopes="true"
    )
    session["state"] = state
    return redirect(authorization_url)


@user_blueprint.post("/setting/pushover")
@login_required
def pushover():
    user_key = request.form.get("pushover")
    if user_key:
        current_user.pushover = user_key
        flash("Pushover user key validate and saved", "success")
    else:
        del current_user.pushover
        flash("Pushover user key deleted", "success")
    return redirect(url_for("user.setting"))


@user_blueprint.get("/setting/youtube/oauth_callback")
@login_required
def setting_youtube_oauth_callback():
    flow = youtube.build_flow(state=session["state"])
    flow.fetch_token(authorization_response=request.url)
    try:
        current_user.youtube = flow.credentials
    except (TypeError, ValueError) as error:
        flash(f"YouTube Access Failed: {error}", "danger")
    else:
        flash("YouTube Access Granted", "success")
    return redirect(url_for("user.setting"))


@user_blueprint.get("/setting/youtube/revoke")
@login_required
def setting_youtube_revoke():
    del current_user.youtube
    flash("YouTube Access Revoked", "success")
    return redirect(url_for("user.setting"))


@user_blueprint.get("/setting/line-notify/authorize")
@login_required
def setting_line_notify_authorize():
    redirect_uri = url_for("user.setting_line_notify_oauth_callback", _external=True)
    return oauth.LineNotify.authorize_redirect(redirect_uri)  # type: ignore


@user_blueprint.get("/setting/line-notify/oauth_callback")
@login_required
def setting_line_notify_oauth_callback():
    token = oauth.LineNotify.authorize_access_token()  # type: ignore
    current_user.line_notify = token["access_token"]
    flash("Line Notify Access Granted", "success")
    return redirect(url_for("user.setting"))


@user_blueprint.get("/setting/line-notify/revoke")
@login_required
def setting_line_notify_revoke():
    """Revoke User's Line Notify Crendential"""
    try:
        del current_user.line_notify
    except RuntimeError as error:
        flash(str(error), "danger")
    else:
        flash("Line Notify Access Revoke", "success")
    return redirect(url_for("user.setting"))


@user_blueprint.get("/setting/dropbox/authorize")
@login_required
def setting_dropbox_authorize():
    authorize_url = dropbox.build_flow(session).start()
    return redirect(authorize_url)


@user_blueprint.get("/setting/dropbox/oauth_callback")
@login_required
def setting_dropbox_oauth_callback():
    try:
        oauth_result = dropbox.build_flow(session).finish(request.args)
    except BadRequestException:
        abort(400)
    except BadStateException:
        # Session Expire, Start the auth flow again.
        return redirect(url_for("user.setting"))
    except CsrfException:
        # CSRF Not Matched, Raise Error
        abort(403)
    except NotApprovedException:
        # User didn't Grant Access
        return redirect(url_for("user.setting"))
    except ProviderException:
        # I Have no clue of what this is for...?
        abort(403)
    current_user.dropbox = oauth_result
    flash("Dropbx Access Granted", "success")
    return redirect(url_for("user.setting"))


@user_blueprint.get("/setting/dropbox/revoke")
@login_required
def setting_dropbox_revoke():
    """Revoke User's Dropbx Crendential"""
    del current_user.dropbox
    flash("Dropbx Access Revoke", "success")
    return redirect(url_for("user.setting"))

tubee/templates/widgets/action_table.html
<!-- BEGIN Action Infos -->
<table class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Type</th>
      <th scope="col">
        <button
          type="button"
          class="btn btn-success"
          data-toggle="modal"
          data-target="#new-action-modal"
        >
          New
        </button>
      </th>
    </tr>
  </thead>
  <tbody>
    {% for action in actions %}
    <!-- BEGIN Action Row -->
    <tr>
      <th>
        <p class="mb-0">{{ action.name }}</p>
        <a
          href="#"
          class="text-muted clipboard"
          data-clipboard-text="{{ action.id }}"
        >
          <p class="mb-0">{{ action.id }}</p>
        </a>
      </th>
      <td class="align-middle">{{ action.type.value }}</td>
      <td class="align-middle">
        <button
          type="button"
          class="btn btn-secondary"
          data-toggle="modal"
          data-target="#edit-action-modal"
          data-read-endpoint="{{ url_for('api_action.action', action_id=action.id) }}"
          data-edit-endpoint="{{ url_for('api_action.edit', action_id=action.id) }}"
        >
          Edit
        </button>
        <button
          type="button"
          class="btn btn-danger"
          data-toggle="modal"
          data-target="#remove-action-modal"
          data-action-name="{{ action.name }}"
          data-api-endpoint="{{ url_for('api_action.delete', action_id=action.id) }}"
        >
          Remove
        </button>
      </td>
    </tr>
    <!-- END Action Row -->
    {% endfor %}
  </tbody>
</table>
<!-- END Action Infos -->

tubee/templates/widgets/message.html
<!-- prettier-ignore -->
{% set special_message_type = ["secondary", "success", "danger", "warning",
"info", "light", "dark"] %}

<!-- prettier-ignore -->
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<!-- MESSAGE -->
{% if message_float is defined and message_float is true %}
<div id="message-wrapper">
  {% endif %}
  <!-- prettier-ignore -->
  {% for category, message in messages %}
  {% set category = category if category in special_message_type else 'primary' %}
  <div
    id="main-alert"
    class="alert alert-{{ category }} alert-dismissible fade show"
    role="alert"
  >
    {{ message }}
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
    ></button>
  </div>
  {% endfor %}
  <!-- prettier-ignore -->
  {% if message_float is defined and message_float is true %}
</div>
{% endif %} {% endif %}

<!-- prettier-ignore -->
{% endwith %}

tubee/templates/widgets/navbar.html
{% from 'macros/base.html' import api_button %}

<header>
  <nav class="navbar navbar-expand-xl navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a
        id="navbar-main"
        class="navbar-brand"
        href="{{ url_for('main.dashboard') }}"
      >
        <img
          id="hero"
          src="{{ url_for('static', filename='img/tubee_text.png') }}"
          class="d-inline-block align-top"
        />
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbars"
        aria-controls="navbars"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbars">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a
              class="nav-link {{ 'active' if title == 'Subscriptions' }}"
              href="{{ url_for('main.dashboard') }}"
            >
              Subscriptions
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link {{ 'active' if title == 'Tags' }}"
              href="{{ url_for('tag.listing') }}"
            >
              Tags
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link {{ 'active' if title == 'Actions' }}"
              href="{{ url_for('action.listing') }}"
            >
              Actions
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link {{ 'active' if title == 'YouTube Subscription' }}"
              href="{{ url_for('main.youtube_subscription') }}"
            >
              Import
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link {{ 'active' if title == 'Videos' }}"
              href="{{ url_for('main.video') }}"
            >
              Videos
            </a>
          </li>
          {% if current_user.admin is defined and current_user.admin %}
          <li class="nav-item">
            <a
              class="nav-link {{ 'active' if title == 'Admin Dashboard' }}"
              href="{{ url_for('admin.dashboard') }}"
            >
              Admin
            </a>
          </li>
          {% endif %}
        </ul>
        <ul class="navbar-nav">
          {% if current_user.is_authenticated %}
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="dropdown_user"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
              >{{ current_user.username }}</a
            >
            <div class="dropdown-menu" aria-labelledby="dropdown_user">
              <a class="dropdown-item" href="{{ url_for('user.setting') }}"
                >Setting</a
              >
              <a class="dropdown-item" href="{{ url_for('user.logout') }}"
                >Logout</a
              >
            </div>
          </li>
          {% else %}
          <li class="nav-item {{ 'active' if title == 'Login' }}">
            <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
          </li>
          <li class="nav-item {{ 'active' if title == 'Register' }}">
            <a class="nav-link" href="{{ url_for('user.register') }}"
              >Register</a
            >
          </li>
          {% endif %}
        </ul>
        <form id="subscribe-form" class="d-flex">
          <input
            type="text"
            id="channel_id"
            name="channel_id"
            class="form-control me-2"
            placeholder="Channel Name or ID"
            aria-label="Channel Name or ID"
            required
          />
          <!-- prettier-ignore -->
          {{ api_button(
            'Subscribe',
            'api_subscription.create',
            method='POST',
            form_id='subscribe-form',
            classes=['my-2', 'my-sm-0']
          ) }}
        </form>
      </div>
    </div>
  </nav>
</header>

tubee/templates/widgets/pagination.html
{% macro content(pagination) -%}
<!-- prettier-ignore -->
{% set page_from = [pagination.page-5, 1]|max %}
{% set page_to = [pagination.page+5, pagination.pages]|min %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    <li class="page-item {{ 'disabled' if not pagination.has_prev }}">
      <a
        class="page-link"
        href="{{ url_for(request.endpoint, page=pagination.prev_num, **request.view_args) }}"
        aria-label="Previous"
      >
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>

    {% if page_from != 1 %}
    <li class="page-item disabled">
      <a class="page-link">...</a>
    </li>
    {% endif %}

    <!-- prettier-ignore -->
    {% for page in range(page_from, page_to+1) %}
    <li class="page-item {{ 'active' if pagination.page == page }}">
      <a
        class="page-link"
        href="{{ url_for(request.endpoint, page=page, **request.view_args) }}"
        >{{ page }}</a
      >
    </li>
    {% endfor %}

    <!-- prettier-ignore -->
    {% if page_to != pagination.pages %}
    <li class="page-item disabled">
      <a class="page-link">...</a>
    </li>
    {% endif %}

    <li class="page-item {{ 'disabled' if not pagination.has_next }}">
      <a
        class="page-link"
        href="{{ url_for(request.endpoint, page=pagination.next_num, **request.view_args) }}"
        aria-label="Next"
      >
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
{%- endmacro %}

tubee/templates/widgets/stylesheets.html
<!-- STYLESHEETS -->
<!--
    This Widget loads different version of css file from CDN Based on flask config
    * Bootstrap                 5.2.0
    * datatables                1.12.1
    * Font Awesome              5.15.3
    * Github Fork Ribbon        0.2.3 (Dev and Test only)
-->
{% if config.DEBUG or config.TESTING %}

<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.0/css/bootstrap.css"
  integrity="sha512-h1rwF0uB6r2IuEZcyjPrR53bBKN9Wb4yL+w3Rdlzmc3CkBF1gMSFvQIIstnu4bEtYDaKca5ke5S8UBAACRImyg=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>
<link
  rel="stylesheet"
  href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.css"
  integrity="sha512-3g2jlxiWYLcHo9Y/jU2dDJNqDIxN/yU5z9fa8lXIJRPe6aWYxTIVpGu95Jn+kgf/4D4fThWsWF5x4u5oK3lMVQ=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.css"
  integrity="sha512-3icgkoIO5qm2D4bGSUkPqeQ96LS8+ukJC7Eqhl1H5B2OJMEnFqLmNDxXVmtV/eq5M65tTDkUYS/Q0P4gvZv+yA=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.3/gh-fork-ribbon.min.css"
  integrity="sha512-TktJbycEG5Van9KvrSHFUcYOKBroD7QCYkEe73HAutODCw9QTFcvF6fuxioYM1h6THNudK1GjVidazj6EslK4A=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>

{% else %}

<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.0/css/bootstrap.min.css"
  integrity="sha512-XWTTruHZEYJsxV3W/lSXG1n3Q39YIWOstqvmFsdNEEQfHoZ6vm6E9GK2OrF6DSJSpIbRbi+Nn0WDPID9O7xB2Q=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>
<link
  rel="stylesheet"
  href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css"
  integrity="sha512-DYpTY0Ub8eZR1nPIgYG0eNVCWim5dFXr834XUOfrVw/5NNRUrPMl8mpNyHvt+CUjG3TyfV898AYXg9eOS+ekmw=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"
  integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
  integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>

{% endif %}

<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/base.css') }}"
/>