tubee/routes/api_task.py
"""API for Tasks"""

from flask import Blueprint, jsonify
from flask_login import login_required

from ..tasks import channels_renew, list_all_tasks, remove_all_tasks
from ..utils import admin_required

api_task_blueprint = Blueprint("api_task", __name__)
api_task_blueprint.before_request(admin_required)


@api_task_blueprint.get("/list-all")
@login_required
def list_all():
    response = list_all_tasks()
    return jsonify(response)


@api_task_blueprint.get("/remove-all")
@login_required
def remove_all():
    response = remove_all_tasks()
    return response


@api_task_blueprint.get("/<task_id>/status")
@login_required
def status(task_id):
    task = channels_renew.AsyncResult(task_id)
    response = {
        "id": task.id,
        "status": task.status.title(),
        "result": task.result,
        "traceback": task.traceback,
    }
    print(f"{response=}")
    if isinstance(task.result, Exception):
        response["result"] = str(task.result)
        response["traceback"] = task.__dict__["_cache"]["traceback"]
    else:
        response["current"] = task.result.get("current", 1)
        response["total"] = task.result.get("total", 1)
        response["channel_id"] = task.result.get("channel_id", None)
    return response

tubee/templates/admin_component/celery.html
<!-- BEGIN CELERY TASKS -->
<h1>Celery Tasks</h1>
<table
  id="celery-table"
  class="table table-striped table-hover table-responsive"
  data-template-endpoint="{{ url_for('static', filename='component/admin_celery_task.html') }}"
  data-api-endpoint="{{ url_for('api_task.list_all') }}"
>
  <thead class="thead-dark">
    <tr>
      <th scope="col" class="align-middle">Name</th>
      <th scope="col" class="align-middle">Args</th>
      <th scope="col" class="align-middle">ETA</th>
      <th scope="col" class="align-middle">Status</th>
    </tr>
  </thead>
  <tbody></tbody>
</table>
<!-- END CELERY TASKS -->

tubee/templates/admin_component/management.html
<!-- BEGIN MANAGEMENT -->
<h1>Management</h1>
<div class="buttons">
  <button
    type="button"
    id="channel-renew-all"
    class="btn btn-secondary"
    data-api-endpoint="{{ url_for('api_channel.renew_all') }}"
  >
    Renew all channel
  </button>
  <button
    type="button"
    id="channel-renew-all-schedule"
    class="btn btn-secondary"
    data-api-endpoint="{{ url_for('api_channel.renew_all', execution=-1) }}"
  >
    Renew all channel (auto)
  </button>
  <button
    type="button"
    id="channel-renew-all-random"
    class="btn btn-secondary"
    data-api-endpoint="{{ url_for('api_channel.renew_all', execution=-2) }}"
  >
    Renew all channel (random)
  </button>
  <button
    type="button"
    id="task-remove-all"
    class="btn btn-secondary"
    data-api-endpoint="{{ url_for('api_task.remove_all') }}"
  >
    Remove All Task
  </button>
  <a
    class="btn btn-secondary"
    href="{{ url_for('admin.raise_exception') }}"
    role="button"
    >Raise Exception</a
  >
  <a
    class="btn btn-secondary"
    href="{{ url_for('admin.test_logging') }}"
    role="button"
    >Test Logging</a
  >
</div>
<div class="results"></div>
<!-- END MANAGEMENT -->

tubee/templates/admin_component/sitemap.html
<!-- BEGIN SITE MAP -->
<h1>Sitemap</h1>
<table class="table table-hover table-responsive-lg">
  <thead class="thead-dark">
    <tr>
      <th scope="col" class="align-middle">Blueprint</th>
      <th scope="col" class="align-middle">Func</th>
      <th scope="col" class="align-middle">Path</th>
    </tr>
  </thead>
  <tbody>
    {% for item in links|dictsort %} {% set blueprint, rules = item %} {% for
    url, endpoint in rules %}
    <tr>
      {% if loop.first %}
      <th scope="row" class="align-middle" rowspan="{{ loop.length }}">
        {{ blueprint }}
      </th>
      {% endif %}
      <td class="align-middle"><a href="{{ url }}">{{ endpoint }}</a></td>
      <td class="align-middle">{{ url }}</td>
    </tr>
    {% endfor %} {% endfor %}
  </tbody>
</table>
<!-- END SITE MAP -->