tubee/models/user.py
"""User Model"""

import json
from dataclasses import dataclass

import dropbox
import requests
from authlib.integrations.flask_client.apps import FlaskOAuth2App
from dropbox.exceptions import AuthError
from flask import current_app
from flask_login import UserMixin
from google.oauth2.credentials import Credentials
from googleapiclient.errors import HttpError
from loguru import logger
from pushover_complete import PushoverAPI

from .. import bcrypt, db, login_manager, oauth
from ..exceptions import APIError, InvalidAction, ServiceNotAuth


@login_manager.user_loader
def load_user(username):
    """Internal function for user info accessing"""
    return User.query.get(username)


@dataclass
class User(UserMixin, db.Model):  # type: ignore
    """
    username                username for identification (Max:30)
    password_hash           user's hashed login password
    admin                   user is Tubee Admin
    pushover_key            access key to Pushover Service
    youtube_credentials     access credentials to YouTube Service
    subscriptions           User's Subscription to YouTube Channels
    """

    username: str
    admin: bool

    __tablename__ = "user"
    username = db.Column(db.String(32), primary_key=True)
    _password_hash = db.Column(db.LargeBinary(128), nullable=False)
    admin = db.Column(db.Boolean, default=False)
    _pushover_key = db.Column(db.String(32))
    _youtube_credentials = db.Column(db.JSON, nullable=False, default={})
    _line_notify_credentials = db.Column(db.String(64))
    _dropbox_credentials = db.Column(db.JSON, nullable=False, default={})
    notifications = db.relationship(
        "Notification",
        back_populates="user",
        lazy="dynamic",
        cascade="all, delete-orphan",
    )
    subscriptions = db.relationship(
        "Subscription",
        back_populates="user",
        lazy="dynamic",
        cascade="all, delete-orphan",
    )
    tags = db.relationship(
        "Tag", back_populates="user", lazy="dynamic", cascade="all, delete-orphan"
    )
    actions = db.relationship(
        "Action",
        back_populates="user",
        lazy="dynamic",
        overlaps="_actions,subscription",
    )

    def __init__(self, username, password, admin=False, **kwargs):
        self.username = username
        self.password = password
        self.admin = admin
        db.session.add(self)
        db.session.commit()
        logger.info(f"User <{self.username}>: Create")

    def __repr__(self):
        return f"<User: {self.username}>"

    @property
    def actions_global(self):
        """Get Global Actions

        Returns:
            list -- List of Global Actions
        """
        return self.actions.filter_by(channel_id=None, tag_id=None).all()

    @actions_global.setter
    def actions_global(self, actions_global):
        raise ValueError("Global action should be modify directly on action")

    @actions_global.deleter
    def actions_global(self):
        raise ValueError("Global action should be modify directly on action")

    def delete(self):
        """Delete User"""
        db.session.delete(self)
        db.session.commit()
        logger.info(f"User <{self.username}>: Delete")

    @property
    def password(self):
        """Password Property"""
        raise AttributeError("Password is not a readable attribute")

    @password.setter
    def password(self, password):
        if len(password) < 6:
            raise ValueError("Password must be longer than 6 characters")
        if len(password) > 30:
            raise ValueError("Password must be shorter than 30 characters")
        self._password_hash = bcrypt.generate_password_hash(password)
        db.session.commit()

    def check_password(self, password):
        """Return True if provided password is valid to login"""
        return bcrypt.check_password_hash(self._password_hash, password)

    @property
    def pushover(self):
        """Pushover Key

        Returns:
            str -- User's Pushover Key

        Raises:
            ServiceNotAuth -- Raised when user has not setup Pushover key yet.
        """
        if not self._pushover_key:
            raise ServiceNotAuth("Pushover")
        return self._pushover_key

    @pushover.setter
    def pushover(self, key):
        """Pushover Setter

        Validating Key and save iff valid

        Decorators:
            pushover.setter

        Arguments:
            key {str} -- User's pushover key obtain from https://pushover.net

        Raises:
            InvalidAction -- Raised when user gave an invalid user key
        """
        pusher = PushoverAPI(current_app.config["PUSHOVER_TOKEN"])
        response = pusher.validate(key)
        if response["status"] != 1:
            raise InvalidAction("Invalid Pushover User Key")
        self._pushover_key = key
        db.session.commit()

    @pushover.deleter
    def pushover(self):
        """Pushover Deleter

        Remove Key
        """
        self._pushover_key = None
        db.session.commit()

    @property
    def youtube(self):
        """YouTube Service

        build service with user's saved credentials.

        Returns:
            googleapiclient.discovery.Resource -- API-calling-ready YouTube
                                                  Service

        Raises:
            ServiceNotAuth -- Raised when user has not authorized yet.
        """
        from ..utils import youtube

        if not self._youtube_credentials:
            raise ServiceNotAuth("YouTube")
        return youtube.build_youtube_api(self._youtube_credentials)

    @youtube.setter
    def youtube(self, credentials):
        """YouTube Setter

        Validating credentials and save iff valid

        Arguments:
            credentials {google.oauth2.credentials.Credentials} -- User's YouTube
                                                                   Credentials

        Raises:
            InvalidAction -- Raised when provided credentials is not valid
        """
        if not isinstance(credentials, Credentials) or not credentials.valid:
            raise InvalidAction("Invalid Credentials")
        self._youtube_credentials = dict(
            token=credentials.token,
            refresh_token=credentials.refresh_token,
            token_uri=credentials.token_uri,
            client_id=credentials.client_id,
            client_secret=credentials.client_secret,
            scopes=credentials.scopes,
        )
        db.session.commit()

    @youtube.deleter
    def youtube(self):
        """YouTube Deleter

        This Method revoke credentials and delete after action is executed
        successfully.

        Raises:
            APIError -- Raised when revoke encounter issue
                                (not necessarily failed)
        """
        if not self._youtube_credentials:
            raise ServiceNotAuth("YouTube")
        response = requests.post(
            "https://oauth2.googleapis.com/revoke",
            params={"token": self._youtube_credentials["token"]},
            headers={"content-type": "application/x-www-form-urlencoded"},
        )
        error_description = response.json().get("error_description")
        if (
            response.status_code == 200
            or error_description == "Token expired or revoked"
        ):
            self._youtube_credentials = None
            db.session.commit()
            return
        raise APIError(service="YouTube", message=error_description)

    @property
    def dropbox(self):
        """Dropbox Service

        [description]

        Returns:
            [type] -- [description]

        Raises:
            ServiceNotAuth -- Raised when user has not authorized yet.
        """
        if not self._dropbox_credentials:
            raise ServiceNotAuth("Dropbox")
        return dropbox.Dropbox(self._dropbox_credentials["access_token"])

    @dropbox.setter
    def dropbox(self, credentials):
        self._dropbox_credentials = dict(
            access_token=credentials.access_token,
            account_id=credentials.account_id,
            user_id=credentials.user_id,
            url_state=credentials.url_state,
        )
        db.session.commit()

    @dropbox.deleter
    def dropbox(self):
        try:
            self.dropbox.auth_token_revoke()
        except AuthError:
            pass
        self._dropbox_credentials = None
        db.session.commit()

    @property
    def line_notify(self) -> FlaskOAuth2App:
        if not self._line_notify_credentials:
            raise ServiceNotAuth("Line Notify")
        return oauth.LineNotify  # type: ignore

    @line_notify.setter
    def line_notify(self, credentials):
        self._line_notify_credentials = credentials
        db.session.commit()

    @line_notify.deleter
    def line_notify(self):
        response = self.line_notify.post("api/revoke")
        if response.status_code != 200 and response.status_code != 401:
            raise APIError(service="Line Notify", message=response.text)
        self._line_notify_credentials = None
        db.session.commit()

    def get_id(self):
        """Get user's ID

        Returns:
            unicode -- ID that uniquely identifies this user
        """
        return self.username

    # Service Test Functions
    def pushover_configured(self):
        return bool(self._pushover_key)

    def youtube_configured(self):
        return bool(self._youtube_credentials)

    def dropbox_configured(self):
        return bool(self._dropbox_credentials)

    def line_notify_configured(self):
        return bool(self._line_notify_credentials)

    # YouTube Method
    def is_subscribing(self, channel):
        """Check if User is subscribing to a channel"""
        from . import Channel

        if isinstance(channel, Channel):
            channel_id = channel.id
        else:
            channel_id = channel

tubee/routes/user.py
"""Routes involves user credentials"""

from dropbox.oauth import (
    BadRequestException,
    BadStateException,
    CsrfException,
    NotApprovedException,
    ProviderException,
)
from flask import (
    Blueprint,
    abort,
    flash,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from flask_login import current_user  # type: ignore
from flask_login import login_required, login_user, logout_user

from .. import oauth
from ..forms import UserForm
from ..models import User
from ..utils import dropbox, is_safe_url, youtube

current_user: User

user_blueprint = Blueprint("user", __name__)


@user_blueprint.get("/")
@login_required
def setting():
    """User Setting Page"""
    return render_template("user/setting.html")


@user_blueprint.route("/register", methods=["GET", "POST"])
def register():
    """User Register"""
    if current_user.is_authenticated:
        flash("You've already logined!", "success")
        return redirect(url_for("main.dashboard"))
    form = UserForm(submit_label="Register", password_confirm=True)
    if form.validate_on_submit():
        exist_user = User.query.get(form.username.data)
        if not exist_user:
            new_user = User(form.username.data, form.password.data)
            login_user(new_user)
            return redirect(url_for("main.dashboard"))
        flash("The Username is Taken", "warning")
    return render_template("user/register.html", form=form)


@user_blueprint.route("/login", methods=["GET", "POST"])
def login():
    """User Login"""
    if current_user.is_authenticated:
        flash("You've already logined!", "success")
        return redirect(url_for("main.dashboard"))
    form = UserForm(submit_label="Login")
    if form.is_submitted():
        if form.validate():
            query_user = User.query.get(form.username.data)
            if query_user and query_user.check_password(form.password.data):
                login_user(query_user, remember=True)
                redirect_url = request.args.get("next")
                if redirect_url and is_safe_url(redirect_url):
                    return redirect(redirect_url)
                return redirect(url_for("main.dashboard"))
        flash("Invalid username or password.", "warning")
    return render_template("user/login.html", form=form)


@user_blueprint.get("/logout")
@login_required
def logout():
    """User Logout"""
    logout_user()
    flash("You've Logged Out", "success")
    return redirect(url_for("user.login"))


@user_blueprint.route("/change-password", methods=["GET", "POST"])
@login_required
def change_password():
    """Change Password"""
    form = UserForm(
        username=current_user.username, submit_label="Save", password_confirm=True
    )
    if form.validate_on_submit():
        current_user.password = form.password.data
        flash("Password Changed", "success")
        return redirect(url_for("user.setting"))
    return render_template("user/change_password.html", form=form)


@user_blueprint.route("/delete", methods=["GET", "POST"])
@login_required
def delete():
    """Confirm Delete Account"""
    form = UserForm(username=current_user.username, submit_label="Delete")
    if form.validate_on_submit():
        if current_user.check_password(form.password.data):
            current_user.delete()
            logout_user()
            flash("Your Account has been deleted", "success")
            return redirect(url_for("user.login"))
        flash("Invalid username or password.", "warning")
    return render_template("user/delete.html", form=form)


@user_blueprint.get("/setting/youtube/authorize")
@login_required
def setting_youtube_authorize():
    flow = youtube.build_flow()
    authorization_url, state = flow.authorization_url(
        access_type="offline", include_granted_scopes="true"
    )
    session["state"] = state
    return redirect(authorization_url)


@user_blueprint.post("/setting/pushover")
@login_required
def pushover():
    user_key = request.form.get("pushover")
    if user_key:
        current_user.pushover = user_key
        flash("Pushover user key validate and saved", "success")
    else:
        del current_user.pushover
        flash("Pushover user key deleted", "success")
    return redirect(url_for("user.setting"))


@user_blueprint.get("/setting/youtube/oauth_callback")
@login_required
def setting_youtube_oauth_callback():
    flow = youtube.build_flow(state=session["state"])
    flow.fetch_token(authorization_response=request.url)
    try:
        current_user.youtube = flow.credentials
    except (TypeError, ValueError) as error:
        flash(f"YouTube Access Failed: {error}", "danger")
    else:
        flash("YouTube Access Granted", "success")
    return redirect(url_for("user.setting"))


@user_blueprint.get("/setting/youtube/revoke")
@login_required
def setting_youtube_revoke():
    del current_user.youtube
    flash("YouTube Access Revoked", "success")
    return redirect(url_for("user.setting"))


@user_blueprint.get("/setting/line-notify/authorize")
@login_required
def setting_line_notify_authorize():
    redirect_uri = url_for("user.setting_line_notify_oauth_callback", _external=True)
    return oauth.LineNotify.authorize_redirect(redirect_uri)  # type: ignore


@user_blueprint.get("/setting/line-notify/oauth_callback")
@login_required
def setting_line_notify_oauth_callback():
    token = oauth.LineNotify.authorize_access_token()  # type: ignore
    current_user.line_notify = token["access_token"]
    flash("Line Notify Access Granted", "success")
    return redirect(url_for("user.setting"))


@user_blueprint.get("/setting/line-notify/revoke")
@login_required
def setting_line_notify_revoke():
    """Revoke User's Line Notify Crendential"""
    try:
        del current_user.line_notify
    except RuntimeError as error:
        flash(str(error), "danger")
    else:
        flash("Line Notify Access Revoke", "success")
    return redirect(url_for("user.setting"))


@user_blueprint.get("/setting/dropbox/authorize")
@login_required
def setting_dropbox_authorize():
    authorize_url = dropbox.build_flow(session).start()
    return redirect(authorize_url)


@user_blueprint.get("/setting/dropbox/oauth_callback")
@login_required
def setting_dropbox_oauth_callback():
    try:
        oauth_result = dropbox.build_flow(session).finish(request.args)
    except BadRequestException:
        abort(400)
    except BadStateException:
        # Session Expire, Start the auth flow again.
        return redirect(url_for("user.setting"))
    except CsrfException:
        # CSRF Not Matched, Raise Error
        abort(403)
    except NotApprovedException:
        # User didn't Grant Access
        return redirect(url_for("user.setting"))
    except ProviderException:
        # I Have no clue of what this is for...?
        abort(403)
    current_user.dropbox = oauth_result
    flash("Dropbx Access Granted", "success")
    return redirect(url_for("user.setting"))


@user_blueprint.get("/setting/dropbox/revoke")
@login_required
def setting_dropbox_revoke():
    """Revoke User's Dropbx Crendential"""
    del current_user.dropbox
    flash("Dropbx Access Revoke", "success")
    return redirect(url_for("user.setting"))

tubee/templates/user/change_password.html
<!-- prettier-ignore -->
{% extends "base.html" %}
{% set title = "Change Password" %}

<!-- prettier-ignore -->
{% block content %}

<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold">Change Password</h1>
    <form class="needs-validation" method="POST">
      {{ form.csrf_token }}
      <!-- prettier-ignore -->
      <div class="mb-3">
        {{ form.password.label }}
        {% if form.password.errors|length > 0 %}
          {{ form.password(class="form-control is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.password.errors %}
              {{ error }}
                {% if not loop.last %}
                  <br />
                {% endif %}
            {% endfor %}
          </div>
        {% else %}
          {{ form.password(class="form-control") }}
        {% endif %}
      </div>
      <!-- prettier-ignore -->
      <div class="mb-3">
        {{ form.password_confirm.label }}
        {% if form.password_confirm.errors|length > 0 %}
          {{ form.password_confirm(class="form-control is-invalid") }}
          <div class="invalid-feedback">
          {% for error in form.password_confirm.errors %}
            {{ error }}
            {% if not loop.last %}
              <br />
            {% endif %}
          {% endfor %}
          </div>
        {% else %}
          {{ form.password_confirm(class="form-control") }}
        {% endif %}
      </div>
      {{ form.submit(class="btn btn-success btn-lg m-2") }}
    </form>
  </div>
</div>
{% endblock %}

tubee/templates/user/delete.html
<!-- prettier-ignore -->
{% extends "base.html" %}
{% set title = "Change Password" %}

<!-- prettier-ignore -->
{% block content %}
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold">Delete Account</h1>
    <p>
      <strong>Warning</strong>: You are about to delete your account. Type your
      password to delete.
    </p>
    <form class="needs-validation" method="POST">
      {{ form.csrf_token }}
      <!-- prettier-ignore -->
      <div class="mb-3">
        {{ form.password.label }}
        {% if form.password.errors|length > 0 %}
          {{ form.password(class="form-control is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.password.errors %}
              {{ error }}
                {% if not loop.last %}
                  <br />
                {% endif %}
            {% endfor %}
          </div>
        {% else %}
          {{ form.password(class="form-control") }}
        {% endif %}
      </div>
      {{ form.submit(class="btn btn-danger btn-lg m-2") }}
    </form>
  </div>
</div>
{% endblock %}

tubee/templates/user/login.html
<!-- prettier-ignore -->
{% extends "base.html" %}
{% set title = "Login" %}

<!-- prettier-ignore -->
{% block content %}
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    <h1 id="headline" class="display-5 fw-bold">Welcome!</h1>
    <form id="" name="" class="needs-validation" method="POST" novalidate>
      {{ form.csrf_token }}
      <!-- prettier-ignore -->
      <div class="mb-3">
      {{ form.username.label }}
      {% if form.username.errors|length > 0 %}
        {{ form.username(class="form-control is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.username.errors %}
            {{ error }}
            {% if not loop.last %}
              <br />
            {% endif %}
          {% endfor %}
        </div>
      {% else %}
        {{ form.username(class="form-control") }}
      {% endif %}
    </div>
      <!-- prettier-ignore -->
      <div class="mb-3">
      {{ form.password.label }}
      {% if form.password.errors|length > 0 %}
        {{ form.password(class="form-control is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
            {{ error }}
            {% if not loop.last %}
              <br />
            {% endif %}
          {% endfor %}
        </div>
      {% else %}
        {{ form.password(class="form-control") }}
      {% endif %}
    </div>
      {{ form.submit(class="btn btn-primary btn-lg m-2") }}
    </form>
  </div>
</div>
{% endblock %}

tubee/templates/user/register.html
<!-- prettier-ignore -->
{% extends "base.html" %}
{% set title = "Register" %}

<!-- prettier-ignore -->
{% block script %}
<script
  type="text/javascript"
  src="{{ url_for('static', filename='js/login.js') }}"
></script>
{% endblock %}

<!-- prettier-ignore -->
{% block content %}
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    <h1 id="headline" class="display-5 fw-bold">Welcome!</h1>
    <form id="" name="" class="needs-validation" method="POST" novalidate>
      {{ form.csrf_token }}
      <!-- prettier-ignore -->
      <div class="mb-3">
        {{ form.username.label }}
        {% if form.username.errors|length > 0 %}
          {{ form.username(class="form-control is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.username.errors %}
              {{ error }}
              {% if not loop.last %}
                <br />
              {% endif %}
            {% endfor %}
          </div>
        {% else %}
          {{ form.username(class="form-control") }}
        {% endif %}
        <div id="usernameHint" class="form-text">
          Upon registration, you agree to both
          <a href="">Tubee</a>,
          <a href="https://policies.google.com/privacy">Google</a>, and
          <a href="https://www.youtube.com/static?template=terms">YouTube</a>'s
          Terms of Service and Privacy Policy.
        </div>
      </div>
      <!-- prettier-ignore -->
      <div class="mb-3">
        {{ form.password.label }}
        {% if form.password.errors|length > 0 %}
          {{ form.password(class="form-control is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.password.errors %}
              {{ error }}
                {% if not loop.last %}
                  <br />
                {% endif %}
            {% endfor %}
          </div>
        {% else %}
          {{ form.password(class="form-control") }}
        {% endif %}
      </div>
      <!-- prettier-ignore -->
      <div class="mb-3">
        {{ form.password_confirm.label }}
        {% if form.password_confirm.errors|length > 0 %}
          {{ form.password_confirm(class="form-control is-invalid") }}
          <div class="invalid-feedback">
          {% for error in form.password_confirm.errors %}
            {{ error }}
            {% if not loop.last %}
              <br />
            {% endif %}
          {% endfor %}
          </div>
        {% else %}
          {{ form.password_confirm(class="form-control") }}
        {% endif %}
      </div>
      {{ form.submit(class="btn btn-primary btn-lg m-2") }}
    </form>
  </div>
</div>
{% endblock %}

tubee/templates/user/setting.html
<!-- prettier-ignore -->
{% extends "base.html" %}
{% set title = "Setting" %}

<!-- prettier-ignore -->
{% block content %}
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    <h1 id="headline" class="display-5 fw-bold">Setting Panel</h1>

    <div class="mb-3">
      <label for="username" class="form-label">Username</label>
      <input
        type="text"
        class="form-control"
        id="username"
        value="{{ current_user.username }}"
        readonly
      />
    </div>

    <div class="mb-3">
      <label for="password" class="form-label">Password</label>
      <div class="input-group">
        <input
          type="password"
          class="form-control"
          id="password"
          aria-describedby="password-help"
          value=".........."
          readonly
        />
        <a
          href="{{ url_for('user.change_password') }}"
          class="btn btn-outline-secondary"
          >Change Password</a
        >
      </div>
    </div>

    <div class="mb-3">
      <form action="{{ url_for('user.pushover') }}" method="POST">
        <label for="pushover-key" class="form-label">Pushover</label>
        <div class="input-group">
          {% if current_user.pushover_configured() %}
          <input
            type="password"
            class="form-control"
            value=".........."
            aria-label="Pushover User Key"
            readonly
          />
          <button class="btn btn-outline-secondary" type="submit">
            Delete User Key
          </button>
          {% else %}
          <input
            type="text"
            name="pushover"
            class="form-control"
            aria-label="Pushover Key"
          />
          <button class="btn btn-outline-secondary" type="submit">
            Validate and Save
          </button>
          {% endif %}
        </div>
        <div id="pushover-key-help" class="form-text">
          Get your user key by login in
          <a href="https://pushover.net/" target="_blank">Pushover</a>
        </div>
      </form>
    </div>

    <div class="mb-3">
      <label for="youtube-credentials" class="form-label"
        >YouTube Account</label
      >
      <div class="input-group">
        {% if current_user.youtube_configured() %}
        <input
          type="password"
          class="form-control"
          id="youtube-credentials"
          value=".........."
          aria-label="Youtube Revoke"
          aria-describedby="youtube-credentials"
          readonly
        />
        <a
          class="btn btn-outline-secondary"
          href="{{ url_for('user.setting_youtube_revoke') }}"
          role="button"
          id="youtube-revoke"
          >Revoke</a
        >
        {% else %}
        <input
          type="text"
          class="form-control"
          id="youtube-credentials"
          aria-label="Youtube Authorize"
          aria-describedby="youtube-credentials"
          readonly
        />
        <a
          class="btn btn-outline-secondary"
          href="{{ url_for('user.setting_youtube_authorize') }}"
          role="button"
          id="youtube-authorize"
          >Authorize</a
        >
        {% endif %}
      </div>
      <div id="youtube-credentials-help" class="form-text">
        You may also revoke access from
        <a href="https://security.google.com/settings/security/permissions">
          Google's security setting page
        </a>
      </div>
    </div>

    <div class="mb-3">
      <label for="line-notify-credentials" class="form-label"
        >Line Notify Account</label
      >
      <div class="input-group">
        {% if current_user.line_notify_configured() %}
        <input
          type="password"
          class="form-control"
          id="line-notify-credentials"
          value=".........."
          aria-label="Line Notify Revoke"
          aria-describedby="line-notify-credentials"
          readonly
        />
        <a
          class="btn btn-outline-secondary"
          href="{{ url_for('user.setting_line_notify_revoke') }}"
          role="button"
          id="line-notify-revoke"
          >Revoke</a
        >
        {% else %}
        <input
          type="text"
          class="form-control"
          id="line-notify-credentials"
          aria-label="Line Notify Authorize"
          aria-describedby="line-notify-credentials"
          readonly
        />
        <a
          class="btn btn-outline-secondary"
          href="{{ url_for('user.setting_line_notify_authorize') }}"
          role="button"
          id="line-notify-authorize"
          >Authorize</a
        >
        {% endif %}
      </div>
    </div>

    <div class="mb-3">
      <label for="dropbox-credentials" class="form-label"
        >Dropbox Account</label
      >
      <div class="input-group">
        {% if current_user.dropbox_configured() %}
        <input
          type="password"
          class="form-control"
          id="dropbox-credentials"
          value=".........."
          aria-label="Dropbox Revoke"
          aria-describedby="dropbox-credentials"
          readonly
        />
        <a
          class="btn btn-outline-secondary"
          href="{{ url_for('user.setting_dropbox_revoke') }}"
          role="button"
          id="dropbox-revoke"
          >Revoke</a
        >
        {% else %}
        <input
          type="text"
          class="form-control"
          id="dropbox-credentials"
          aria-label="Dropbox Authorize"
          aria-describedby="dropbox-credentials"
          readonly
        />
        <a
          class="btn btn-outline-secondary"
          href="{{ url_for('user.setting_dropbox_authorize') }}"
          role="button"
          id="dropbox-authorize"
          >Authorize</a
        >
        {% endif %}
      </div>
    </div>

    <div class="md-3">
      <a href="{{ url_for('user.delete') }}" class="link-danger"
        >Delete Account</a
      >
    </div>
  </div>
</div>
{% endblock %}