tubee/models/channel.py
"""Channel Model"""

from dataclasses import dataclass
from datetime import datetime, timedelta
from urllib.parse import urlencode

from flask import current_app, url_for
from googleapiclient.errors import Error as YouTubeAPIError
from loguru import logger

from .. import db
from ..exceptions import APIError, InvalidAction


@dataclass
class Channel(db.Model):  # type: ignore
    """
    update:        Update metadata from YouTube API
    refresh:       Refresh subscription status from Hub
    subscribe:     Subscribe callback from Hub
    """

    id: str
    name: str
    active: bool
    infos: dict
    hub_infos: dict
    subscribe_timestamp: datetime
    unsubscribe_timestamp: datetime

    __tablename__ = "channel"
    RENEW_INTERVAL = int(timedelta(days=4).total_seconds())
    id = db.Column(db.String(32), primary_key=True)
    name = db.Column(db.String(128))
    active = db.Column(db.Boolean, default=False)
    infos = db.Column(db.JSON, nullable=False, default={})
    hub_infos = db.Column(db.JSON, nullable=False, default={})
    subscribe_timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    unsubscribe_timestamp = db.Column(db.DateTime)
    actions = db.relationship(
        "Action", back_populates="channel", overlaps="subscription"
    )
    videos = db.relationship(
        "Video", back_populates="channel", lazy="dynamic", cascade="all, delete-orphan"
    )
    callbacks = db.relationship(
        "Callback",
        back_populates="channel",
        lazy="dynamic",
        cascade="all, delete-orphan",
    )
    subscriptions = db.relationship(
        "Subscription",
        back_populates="channel",
        lazy="dynamic",
        cascade="all, delete-orphan",
    )

    def __init__(self, channel_id):
        from ..tasks import channels_fetch_videos, channels_refresh, channels_renew

        self.id = channel_id
        db.session.add(self)
        db.session.commit()
        try:
            self.update()
            logger.info(f"Channel <{self.id}>: Create")
        except (APIError, InvalidAction) as error:
            db.session.delete(self)
            db.session.commit()
            logger.exception(f"Channel <{channel_id}>: Create failed with API Error")
            raise error

        channels_refresh.apply_async(
            args=[[channel_id]],
            countdown=60,
        )
        channels_fetch_videos.apply_async(args=[[channel_id]])
        channels_renew.apply_async(args=[[channel_id], 345600], countdown=345600)
        self.activate()

    def __repr__(self):
        return f"<Channel <{self.id}> ({self.name})>"

    @property
    def expiration(self):
        from ..utils import try_parse_datetime

        try:
            return try_parse_datetime(self.hub_infos["expiration"])
        except (TypeError, KeyError):
            return None

    @expiration.setter
    def expiration(self, expiration):
        raise ValueError("expiration can not be set")

    @expiration.deleter
    def expiration(self):
        raise ValueError("expiration can not be delete")

    @property
    def renewal(self):
        expiration = self.expiration
        tomorrow = datetime.now() + timedelta(days=1)
        if expiration is None:
            # Expiration is not available yet (Channel just init)
            renewal = datetime.now() + timedelta(seconds=self.RENEW_INTERVAL)
        elif expiration > tomorrow:
            # Expiration is more than one day
            renewal = expiration - timedelta(days=1)
        else:
            # Expiration is less than one day
            renewal = datetime.now()
        return renewal

    @renewal.setter
    def renewal(self, renewal):
        raise ValueError("renewal can not be set")

    @renewal.deleter
    def renewal(self):
        raise ValueError("renewal can not be delete")

    def activate(self):
        """Submitting hub Subscription, called when first user subscribe"""
        if self.active:
            raise AttributeError("Channel is already active")
        results = self.subscribe()
        if not results:
            raise RuntimeError("Channel activate failed")
        self.active = True
        self.subscribe_timestamp = datetime.utcnow()
        db.session.commit()
        logger.info(f"Channel <{self.id}>: Activate")
        return results

    def deactivate(self):
        """Submitting hub unsubscription, called when last user unsubscribe"""
        from ..utils import hub

        if not self.active:
            raise AttributeError("Channel is already deactivate")
        callback_url = url_for(
            "main.channel_callback", channel_id=self.id, _external=True
        )
        topic_url = current_app.config["HUB_YOUTUBE_TOPIC"] + urlencode(
            {"channel_id": self.id}
        )
        response = hub.unsubscribe(
            current_app.config["HUB_GOOGLE_HUB"], callback_url, topic_url
        )
        if response.success:
            self.active = False
            self.unsubscribe_timestamp = datetime.utcnow()
            db.session.commit()
            logger.info(f"Channel <{self.id}>: Deactivate")
        else:
            logger.error(f"Channel <{self.id}>: Deactivate failed")
        return response

    def refresh(self):
        """Update hub subscription details, called by task or app"""
        from ..utils.hub import details

        callback_url = url_for(
            "main.channel_callback", channel_id=self.id, _external=True
        )
        topic_url = current_app.config["HUB_YOUTUBE_TOPIC"] + urlencode(
            {"channel_id": self.id}
        )
        results = details(current_app.config["HUB_GOOGLE_HUB"], callback_url, topic_url)
        results.pop("requests_url")
        results.pop("response_object")
        response = results.copy()
        for key, val in results.items():
            if not val:
                continue
            if isinstance(val, datetime):
                results[key] = str(val)
            elif isinstance(val[0], datetime):
                results[key] = (str(val[0]), val[1])
        self.hub_infos = results
        db.session.commit()
        logger.info(f"Channel <{self.id}>: Hub info updated")
        return response

    def update(self):
        """Update YouTube metadata, called by task"""
        from ..utils.youtube import build_youtube_api

        try:
            api_result = (
                build_youtube_api()
                .channels()
                .list(part="snippet", id=self.id)
                .execute()
            )
            if "items" not in api_result:
                if self.name is None:
                    raise InvalidAction(
                        f"Channel <{self.id}>: YouTube info update failed, "
                        "doesn't exists"
                    )
                raise APIError(
                    service="YouTube",
                    message=f"Unable to update channel <{self.id}> info",
                )
            self.infos = api_result["items"][0]
            self.name = self.infos["snippet"]["title"]
            db.session.commit()
            logger.info(f"Channel <{self.id}>: YouTube info updated")
            return self.infos
        except (YouTubeAPIError, KeyError) as error:
            # TODO: Parse API Error
            logger.exception(f"Channel <{self.id}>: YouTube info update failed")
            raise APIError(
                service="YouTube",
                message=str(error.args),
                error_type=error.__class__.__name__,
            )

    def subscribe(self):
        """Submitting hub Subscription, called by task or app"""
        from ..utils.hub import subscribe

        callback_url = url_for(
            "main.channel_callback", channel_id=self.id, _external=True
        )
        topic_url = current_app.config["HUB_YOUTUBE_TOPIC"] + urlencode(
            {"channel_id": self.id}
        )
        response = subscribe(
            current_app.config["HUB_GOOGLE_HUB"], callback_url, topic_url
        )
        logger.debug(f"Callback URL: {callback_url}")
        logger.debug(f"Topic URL   : {topic_url}")
        logger.debug(f"Channel ID  : {self.id}")
        logger.debug(f"Response    : {response.status_code}")
        logger.info(f"Channel <{self.id}>: Hub Subscribe")
        return response.success

    def fetch_videos(self, fetch_all=False):
        """Update videos, Called by task"""
        from ..utils.youtube import build_youtube_api
        from .video import Video

        search = build_youtube_api().search()
        request = search.list(
            part="snippet",
            channelId=self.id,
            maxResults=50,
            order="date",
            type="video",
            fields=Video.DETAILS_FIELDS,
        )

        results = {"new_item_appended": 0, "video_ids": []}
        while request is not None:
            api_results = request.execute()
            for video in api_results["items"]:
                video_id = video["id"]["videoId"]
                if not Video.query.get(video_id):
                    Video(video_id, self, details=video["snippet"])
                    results["new_item_appended"] += 1
                    results["video_ids"].append(video_id)
            if not fetch_all:
                request = search.list_next(request, api_results)
            else:
                break

        logger.info(f"Channel <{self.id}>: Video Fetched")
        return results

tubee/models/tag.py
"""Tag Model"""

from dataclasses import dataclass

from loguru import logger

from .. import db


@dataclass
class Tag(db.Model):  # type: ignore
    """Tag for grouping subscriptions"""

    id: int
    username: str
    name: str

    __tablename__ = "tag"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(32), db.ForeignKey("user.username"), nullable=False)
    name = db.Column(db.String(64), index=True, nullable=False)
    sort_index = db.Column(db.Integer)
    user = db.relationship("User", back_populates="tags")
    subscription_tags = db.relationship(
        "SubscriptionTag",
        back_populates="tag",
        lazy="dynamic",
        cascade="all, delete-orphan",
    )
    actions = db.relationship(
        "Action", back_populates="tag", lazy="dynamic", cascade="all, delete-orphan"
    )

    def __init__(self, username, tag_name):
        self.username = username
        self.name = tag_name
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f"<{self.username}'s Tag: {self.name}>"

    def rename(self, new_name):
        """Rename the tag"""
        self.name = new_name
        db.session.commit()
        logger.info(f'Tag <{self.id}>: Rename to "{new_name}"')
        return self

    def set_sort_index(self, sort_index):
        """Set the sort index"""
        self.sort_index = sort_index
        db.session.commit()
        logger.info(f"Tag <{self.id}>: Set sort index to {sort_index}")
        return self

    def delete(self):
        """Delete the tag"""
        tag_id = self.id
        try:
            db.session.delete(self)
            db.session.commit()
            logger.info(f"Tag <{tag_id}>: Remove")
            return self
        except Exception as error:
            # TODO: not sure if this is the right way to handle this
            logger.exception(f"Tag <{tag_id}>: Remove failed")
            raise error

tubee/routes/main.py
"""The Main Routes"""

import bs4
from flask import Blueprint, jsonify, render_template, request
from flask_login import current_user  # type: ignore
from flask_login import login_required
from loguru import logger

from .. import db
from ..forms import ActionForm
from ..models import Callback, Channel, User, Video

current_user: User

main_blueprint = Blueprint("main", __name__)


@main_blueprint.get("/")
@login_required
def dashboard():
    """Showing Subscribed Channels with specified tag"""

    # Fetching all subscribed channels
    subscriptions = current_user.subscriptions.outerjoin(Channel).order_by(
        Channel.name.asc()
    )

    # Paginate subscriptions
    page = request.args.get("page", 1, type=int)
    pagination = subscriptions.paginate(page=page, per_page=25, error_out=False)
    return render_template(
        "subscription/main.html",
        subscription_pagination=pagination,
        tag=None,
        actions=None,
    )


@main_blueprint.get("/subscription/youtube")
@login_required
def youtube_subscription():
    return render_template("subscription/youtube.html")


@main_blueprint.get("/channel/<channel_id>")
def channel(channel_id):
    subscription = current_user.subscriptions.filter_by(
        channel_id=channel_id
    ).first_or_404()

    # Paginate videos
    page = request.args.get("page", 1, type=int)
    videos = subscription.channel.videos.order_by(Video.uploaded_timestamp.desc())
    pagination = videos.paginate(page=page, per_page=25, error_out=False)
    return render_template(
        "channel.html",
        subscription=subscription,
        action_form=ActionForm(),
        video_pagination=pagination,
    )


@main_blueprint.get("/channel/<channel_id>/callback")
def channel_callback_subscribe(channel_id):
    """Receive Hub Challenges to sustain subscription"""
    channel_item = Channel.query.get_or_404(channel_id)
    callback_item = Callback(channel_item)
    infos = {
        "method": request.method,
        "arguments": request.args,
        "user_agent": str(request.user_agent),
    }
    response = request.args.to_dict().get("hub.challenge")
    if response:
        callback_item.type = "Hub Challenge"
        infos["details"] = response
        callback_item.infos = infos
    else:
        response = callback_item.type = "Unknown GET Request"
    db.session.commit()
    return response


# TODO: REBUILD THIS
@main_blueprint.post("/channel/<channel_id>/callback")
def channel_callback(channel_id):
    """Receive Hub Notifications"""
    channel_item = Channel.query.get_or_404(channel_id)
    callback_item = Callback(channel_item)
    infos = {
        "method": request.method,
        "arguments": request.args,
        "user_agent": str(request.user_agent),
    }

    # Preprocessing
    infos["data"] = request.get_data(as_text=True)
    soup = bs4.BeautifulSoup(infos["data"], "xml")
    response = {}
    # TODO: Inspecting

    tag = soup.find("yt:videoId")
    if tag is None:
        logger.info(f"Video ID not Found for {callback_item}")
        callback_item.infos = infos
        db.session.commit()
        return response
    video_id = tag.string

    # Update Database Records
    video_item = Video.query.get(video_id)
    new_video = not bool(video_item)
    if new_video:
        video_item = Video(video_id, channel_item)
    video_item.callbacks.append(callback_item)
    callback_item.video = video_item
    callback_item.type = "Hub Notification"
    callback_item.infos = infos
    db.session.commit()

    # Pass actions if not new video
    if not new_video:
        return jsonify(response)

    # List users and execute actions
    for sub in channel_item.subscriptions:
        for action in sub.automated_actions:
            try:
                results = action.execute(
                    video_id=video_id,
                    video_title=video_item.name,
                    video_description=video_item.details["description"],
                    video_thumbnail=video_item.details["thumbnails"]["medium"]["url"],
                    video_thumbnail_small=video_item.details["thumbnails"]["default"][
                        "url"
                    ],
                    video_file_url=video_item.video_file_url,
                    channel_name=channel_item.name,
                )
            except Exception as error:
                results = {
                    "error": error.__class__.__name__,
                    "description": str(error),
                }
                logger.exception(f"{channel_id}-{action.id}: {error}")
            else:
                logger.info(f"{channel_id}-{action.id}")
            response[action.id] = results
    return jsonify(response)


@main_blueprint.get("/video")
@login_required
def video():
    return render_template("video/main.html")

tubee/routes/tag.py
from flask import Blueprint, render_template
from flask_login import current_user  # type: ignore
from flask_login import login_required

from ..models import Tag, User

current_user: User

tag_blueprint = Blueprint("tag", __name__)


@tag_blueprint.get("/")
@login_required
def listing():
    tags = current_user.tags.order_by(Tag.sort_index.asc()).all()
    subscriptions = current_user.subscriptions.all()
    return render_template("tag/listing.html", tags=tags, subscriptions=subscriptions)


@tag_blueprint.get("/<tag_id>")
@login_required
def main(tag_id: int):
    """Showing Subscribed Channels with specified tag"""
    tag = Tag.query.get_or_404(tag_id, "Tag not found")
    actions = current_user.actions.join(Tag).filter(Tag.id == tag_id).all()
    return render_template("tag/main.html", tag=tag, actions=actions)

tubee/templates/actions.html
<!-- prettier-ignore -->
{% import 'action/table.html' as action_table with context %}

<!-- prettier-ignore -->
{% extends "base.html" %}
{% set title = "Actions" %}

<!-- prettier-ignore -->
{% block script %}
<script src="{{ url_for('static', filename='js/action_table.js') }}"></script>
<script src="{{ url_for('static', filename='js/modal_edit.js') }}"></script>
{% endblock %}

<!-- prettier-ignore -->
{% block content %}
{{ action_table.content(actions, show_scope=True) }}
{% endblock %}

tubee/templates/admin.html
<!-- prettier-ignore -->
{% extends "base.html" %}
{% set title = "Admin Dashboard" %}

<!-- prettier-ignore -->
{% block script %}
<script src="{{ url_for('static', filename='js/admin.js') }}"></script>
{% endblock %}

<!-- prettier-ignore -->
{% block content %}

{% set tabs = {
  "sitemap": "Sitemap",
  "channels": "Channels",
  "celery_tasks": "Celery Tasks",
  "management": "Management",
  "notifications": "Notifications",
  "sys_runtime": "System Runtime",
  "app_config": "Application Config",
  "envs": "Environment Variables",
} %}

<!-- BEGIN TABS -->
<ul class="nav nav-tabs" id="myTab" role="tablist">
  {% for key, name in tabs.items() %}
  <li class="nav-item">
    <button
      class="nav-link {{ 'active' if loop.first else '' }}"
      id="{{ key }}-tab"
      data-bs-toggle="tab"
      data-bs-target="#{{ key }}"
      type="button"
      role="tab"
      aria-controls="{{ key }}"
      aria-selected="{{ 'true' if loop.first else 'false' }}"
    >
      {{ name }}
    </button>
  </li>
  {% endfor %}
</ul>
<!-- END TABS -->

<!-- BEGIN TAB PAGES -->
<div id="admin-dashbaord-tab-content" class="tab-content">
  {% for key in tabs %}
  <div
    class="tab-pane fade {{ 'show active' if loop.first else '' }}"
    id="{{ key }}"
    role="tabpanel"
    aria-labelledby="{{ key }}-tab"
  >
    {% include 'component/admin_' + key + '.html' %}
  </div>
  {% endfor %}
</div>
<!-- END TAB PAGES -->

{% endblock %}

tubee/templates/base.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <link rel="icon" href="{{ url_for('static', filename='favicon.png') }}" />
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no"
    />
    <title>Tubee - {{ title }}</title>
    <!-- prettier-ignore -->
    {% include "widgets/preloads.html" %}
    {% include "widgets/stylesheets.html" %}
    <!-- PAGE CSS -->
    {% block style %}{% endblock %}
  </head>
  <body
    class="d-flex flex-column h-100"
    data-sitemap="{{ sitemap | tojson | forceescape }}"
  >
    {% include "widgets/navbar.html" %}
    <main role="main" class="flex-grow-1">
      <!-- CONTAINER -->
      <div id="content-container" class="container h-100">
        {% include "widgets/message.html" %}
        <!-- CONTENT -->
        {% block content %}{% endblock %}
      </div>
      <div id="hidden-container"></div>
    </main>
    <!-- FOOTER -->
    <footer class="footer mt-auto py-3">
      <div class="container text-muted text-center">
        <span class="line">Copyright © 2021 Tomy Hsieh.</span>
        <span class="line">All rights reserved.</span>
      </div>
    </footer>

    {% if config.DEBUG %}
    <!-- RIBBON -->
    <a
      class="github-fork-ribbon right-bottom fixed"
      href="#"
      data-ribbon="Development Build"
    ></a>
    {% elif config.TESTING %}
    <!-- RIBBON -->
    <a
      class="github-fork-ribbon right-bottom fixed"
      href="#"
      data-ribbon="Testing Build"
    ></a>
    {% endif %}
    <!-- prettier-ignore -->
    {% include "widgets/scripts.html" %}
    <!-- PAGE JS -->
    {% block script %}{% endblock %}
  </body>
</html>

tubee/templates/channel.html
<!-- prettier-ignore -->
{% from 'macros/action.html' import table %}
{% from 'macros/channel.html' import carousal, info %}
{% import 'video/table.html' as video_table with context %}
{% import 'widgets/pagination.html' as pagination %}

<!-- prettier-ignore -->
{% extends "base.html" %}
{% set channel = subscription.channel %}
{% set title = channel.name %}

<!-- prettier-ignore -->
{% block style %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/channel.css') }}"
/>
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/subscription_tag.css') }}"
/>
{% endblock %}

<!-- prettier-ignore -->
{% block script %}
<script src="{{ url_for('static', filename='js/action.js') }}"></script>
{% endblock %}

<!-- prettier-ignore -->
{% block content %}
{% if video_pagination.items %}
  {{ carousal(video_pagination.items) }}
{% endif %}
{{ info(channel, subscription, current_user) }}
{{ table(subscription.actions, channel_id=channel.id) }}
{% if video_pagination.items %}
  {{ video_table.content(video_pagination.items) }}
  {{ pagination.content(video_pagination) }}
{% endif %}
{% endblock %}

tubee/templates/dashboard.html
{% from "widgets/callback_badge.html" import badge %} {% extends "base.html" %}
{% set title = "Dashboard" %} {% block style %}
<link
    rel="stylesheet"
    href="{{ url_for('static', filename='css/dashboard.css') }}"
/>
{% endblock %} {% block script %}
<script src="{{ url_for('static', filename='js/dashboard.js') }}"></script>
{% endblock %} {% block content %}

<!-- BEGIN Toggle View -->
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-end">
        <li class="page-item">
            <a class="page-link" href="#">
                <i class="fas fa-list"></i>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="#">
                <i class="fas fa-portrait"></i>
            </a>
        </li>
    </ul>
</nav>
<!-- END Toggle View -->

<!-- BEGIN Subscription Table -->
<table class="table table-striped table-hover table-responsive-lg">
    <thead class="thead-dark">
        <tr>
            <th scope="col" class="align-middle"></th>
            <th scope="col" class="align-middle">Channel Name</th>
            <th scope="col" class="align-middle">Recent Activity</th>
            <th scope="col" class="align-middle"></th>
            {% if current_user.admin %}
            <th scope="col" class="align-middle">Hub Status</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for subscription in subscriptions %}
        <tr>
            <th scope="row" class="align-middle channel-thumbnails">
                {% if subscription.channel.infos.snippet.thumbnails.high.url %}
                <img
                    src="{{ subscription.channel.infos.snippet.thumbnails.high.url }}"
                    class="rounded-circle"
                />
                {% endif %}
            </th>
            <td class="align-middle channel-name">
                <a
                    href="{{ url_for('main.channel', channel_id=subscription.channel_id) }}"
                >
                    <p class="mb-0">{{ subscription.channel.name }}</p>
                </a>
                <a
                    href="#"
                    class="text-muted clipboard"
                    data-clipboard-text="{{ subscription.channel_id }}"
                >
                    <p class="mb-0">{{ subscription.channel_id }}</p>
                </a>
                {% if subscription.channel.infos.snippet.customUrl %}
                <a
                    href="#"
                    class="text-muted clipboard"
                    data-clipboard-text="{{ subscription.channel.infos.snippet.customUrl }}"
                >
                    <p class="mb-0">
                        #{{ subscription.channel.infos.snippet.customUrl }}
                    </p>
                </a>
                {% endif %}
            </td>
            <td class="align-middle"></td>
            <td class="align-middle">
                <button
                    type="button"
                    class="btn btn-danger unsubscribe-btn"
                    data-channel-name="{{ subscription.channel.name }}"
                    data-api-endpoint="{{ url_for('api_channel.unsubscribe', channel_id=subscription.channel_id) }}"
                >
                    Unsubscribe
                </button>
                {% if current_user.admin %}
                <button
                    class="btn btn-warning renew-btn"
                    type="button"
                    data-renew-url="{{ url_for('api_channel.renew', channel_id=subscription.channel_id) }}"
                >
                    Renew
                </button>
                {% endif %}
            </td>
            {% if current_user.admin %}
            <td class="align-middle">
                {{ badge(subscription.channel.hub_infos.state) }}
                <br />
                <span class="badge badge-warning"
                    >{{ moment(subscription.channel.expiration).fromNow()
                    }}</span
                >
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>
<!-- END Subscription Table -->

{% endblock %}

tubee/templates/error.html
<!-- prettier-ignore -->
{% extends "base.html" %}
{% set title = "It's an Error!" %}
{% set message_float = True %}

<!-- prettier-ignore -->
{% block style %}
<link
  rel="stylesheet"
  type="text/css"
  href="https://fonts.googleapis.com/css?family=Baloo+Bhaijaan"
/>
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static', filename='css/error.css') }}"
/>
{% endblock %}

<!-- prettier-ignore -->
{% block content %}
<div id="hero" class="row h-100">
  <div class="col-sm-6 my-auto">
    <img
      class="img-fluid"
      src="{{ url_for('static', filename='img/ripped.jpg') }}"
    />
  </div>
  <div class="col-sm-6 my-auto">
    <h1 class="display-1 m-0">Oops !</h1>
    <h1 class="m-0">You've ripped a hole in the fabric of the internet !!!</h1>
    <small class="text-muted">
      <a href="{{ url_for('main.dashboard') }}">Return to the Safe Place</a>
    </small>
  </div>
</div>
{% endblock %}

tubee/templates/map.html
{% extends "base.html" %}
{% set title = "Sitemap" %}

{% block content %}
<table class="table table-striped table-hover table-responsive-lg">
    <thead class="thead-dark">
        <tr>
            <th scope="col" class="align-middle">Func</th>
            <th scope="col" class="align-middle">Path</th>
        </tr>
    </thead>
    <tbody>
        {% for url, endpoint in links %}
        <tr>
            <th scope="row" class="align-middle">
                <a href="{{ url }}">{{ endpoint }}</a>
            </th>
            <td class="align-middle">
                {{ url }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

tubee/templates/tags.html
<!-- prettier-ignore -->
{% extends "base.html" %}
{% set title = "Tags" %}

<!-- prettier-ignore -->
{% block style %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/tags.css') }}"
/>
{% endblock %}

<!-- prettier-ignore -->
{% block content %}

<!-- BEGIN Tag Grid -->
<div class="row row-cols-1 row-cols-md-3 g-4">
  <!-- prettier-ignore -->
  {% for tag in tags %}
  <div class="col">
    <div class="card">
      <div
        class="card-header d-flex align-items-center justify-content-between"
      >
        <a
          href="{{ url_for('main.dashboard', tag_id=tag.id) }}"
          class="stretched-link"
        >
          <h5 class="card-title m-0">{{ tag.name }}</h5>
        </a>
        <span class="badge bg-secondary rounded-pill"
          >{{ tag.subscription_tags.count() }}</span
        >
      </div>
      <ul class="list-group list-group-flush">
        {% for subscription_tag in tag.subscription_tags %}
        <li class="list-group-item">
          <!-- prettier-ignore -->
          {% if subscription_tag.subscription.channel.infos.snippet.thumbnails.high.url %}
          <!-- prettier-ignore -->
          <img
            src="{{ subscription_tag.subscription.channel.infos.snippet.thumbnails.high.url }}"
            class="tags-channel-thumbnails rounded-circle"
          />
          {% endif %}
          <a
            href="{{ url_for('main.channel', channel_id=subscription_tag.channel_id) }}"
            class="stretched-link p-2"
          >
            {{ subscription_tag.subscription.channel.name }}
          </a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  {% endfor %}
  <div class="col">
    <div class="card">
      <div
        class="card-header d-flex align-items-center justify-content-between"
      >
        <a
          href="{{ url_for('main.dashboard', tag_id=None) }}"
          class="stretched-link"
        >
          <h5 class="card-title m-0">Untagged</h5>
        </a>
      </div>
      <ul class="list-group list-group-flush"></ul>
    </div>
  </div>
</div>
<!-- END Tag Grid -->

{% endblock %}